-- Highlight todo, notes, etc in comments
-- TODO: We're skipping the expressions until we encounter a semicolon
-- HACK: Some test hack
-- WARNING: Longer than warn?
-- WARN: test
-- XXX: bad content
-- PERF: Performance or optimization something
-- PERFORMANCE: a perf note
-- OPTIMIZE: a optimization note
-- OPTIM: shorthand
-- INFO: This is some info
-- NOTE: Like what I did here?
-- FIX: test fix
-- BUG: this is a bug
-- FIXME:
-- FIXIT:
-- ISSUE:
-- TEST: A test!
-- TESTING: under test
-- PASSED: passed test
-- FAILED: failed test
-- IDEA: This is an idea!
-- CONF: This is configuration info
-- CONFIG: Also config info
